### ISSUE TITLE
promisify the non-worker mode

### ISSUE THREAD

**Issue by NPellet** [cheminfo-js/jcampconverter#5]
At least it should clearly be stated otherwise.

**Comment by targos** [comment]
You gain nothing by promisifying the synchronous mode. It will still block your page during the conversion.
Do you think the documentation needs to be more explicit about what is returned when useWorker is false ?

**Comment by NPellet** [comment]
Whether the worker is used or not, it might be nice to have the same return
of .convert() (i.e. a promise)

If you don't want that, you should state it more clearly in the docs,
because I got it wrong on the first try...


2015-05-29 8:51 GMT+02:00 Michaël Zasso <notifications@github.com>:
